environments:
  dataspace:
    SNOWSQL_ACCOUNT: coxasph-epb76465
    SNOWSQL_USER: Erick
    SNOWSQL_PWD: Accenture2024!@
    SNOWSQL_ROLE: ACCOUNTADMIN
    SNOWSQL_DATABASE: BANANA_QUALITY
    SNOWSQL_WAREHOUSE: COMPUTE_WH
    SNOWFLAKE_SCHEMA: EXP
    STAGE_NAME: ML_MODELS
    TRAIN_DIR: TRAIN_PIPELINE
    INFERENCE_DIR: INFERENCE_PIPELINE
    MODEL_NAME: BANANA_MODEL


