environments:
  dataspace:
    accountname: coxasph-epb76465
    username: Erick
    password: Accenture2024!@
    rolename: ACCOUNTADMIN
    dbname: BANANA_QUALITY
    warehousename: COMPUTE_WH
    schemaname: EXP
    STAGE_NAME: ML_MODELS
    TRAIN_DIR: TRAIN_PIPELINE
    INFERENCE_DIR: INFERENCE_PIPELINE
    MODEL_NAME: BANANA_MODEL

  validate:
    accountname: coxasph-epb76465

  live:
    accountname: coxasph-epb76465

