environments:
  dataspace:
    accountname: coxasph-epb76465
    username: Erick
    password: Accenture2024!@
    rolename: ACCOUNTADMIN
    dbname: BANANA_QUALITY
    warehousename: COMPUTE_WH
    sf_schema: EXP
    stage_name: ML_MODELS
    train_dir: TRAIN_PIPELINE
    inference_dir: INFERENCE_PIPELINE
    model_name: BANANA_MODEL

  validate:
    variable1: valor_variable1

  live:
    variable2: valor_variable2

