name: snowflake-dataops-exp

# Controls when the action will run. 
on:
  push:
    branches:
      - exp

jobs:
  setup_snowflake_workspace_exp:
    runs-on: ubuntu-latest
    environment: EXP
    env:
      ENV_NAME: "exp"
      

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install Python packages
        run: pip install -r requirements.txt

      - name: Set up Snowflake
        uses: ErickPerezArgueta/composite_sf@main
        with:
          SNOWSQL_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SNOWSQL_USER: ${{ secrets.SF_USERNAME }}
          SNOWSQL_PWD: ${{ secrets.SF_PASSWORD }}
          SNOWSQL_ROLE: ${{ vars.SF_ROLE }}
          SNOWSQL_WAREHOUSE: ${{ vars.SF_WAREHOUSE }}
          SNOWSQL_DATABASE: ${{ vars.SF_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ vars.SF_SCHEMA_EXP }}
          ENV_NAME: ${{ env.ENV_NAME }}

      # - name: Cache previous GITHUB_SHA
      #   id: cache-sha
      #   uses: actions/cache@v3
      #   with:
      #     path: .github/previous_sha
      #     key: previous-sha
      
      - name: Save current GITHUB_SHA
        run: |
          echo "${GITHUB_SHA}" > .github/previous_sha/current_sha.txt
          echo CURRENT_SHA: ${GITHUB_SHA} >> "$GITHUB_ENV" 

      # - name: Get previous GITHUB_SHA
      #   id: get-previous-sha
      #   run: |
      #     if [ -f .github/previous_sha/current_sha.txt ]; then
      #       PREVIOUS_SHA=$(cat .github/previous_sha/current_sha.txt)
      #       echo "PREVIOUS_SHA=${PREVIOUS_SHA}" >> $GITHUB_ENV
      #     fi
                  

      - name: Creates pipeline
        env:
          STAGE_NAME: ${{vars.STAGE_NAME}}
          TRAIN_DIR: ${{vars.TRAIN_DIR}}
          INFERENCE_DIR: ${{vars.INFERENCE_DIR}}
          MODEL_NAME: ${{vars.MODEL_NAME}}
          CURRENT_SHA: ${{ env.CURRENT_SHA }}
        run: 
         python $GITHUB_WORKSPACE/src/dags/dag_tasks.py