name: snowflake-dataops-validate

# Controls when the action will run. 
on:
  pull_request:
    branches:
      - validate
    types: [opened, synchronize]

jobs:
  setup_snowflake_workspace_validate:
    if: github.event.pull_request.base.ref == 'validate' && github.event.pull_request.head.ref == 'exp'
    runs-on: ubuntu-latest
    environment: VALIDATE
    env:
      ENV_NAME: "validate"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install Python packages
        run: pip install -r requirements.txt

      - name: Set up Snowflake
        uses: ErickPerezArgueta/composite_sf@main
        with:
          SNOWSQL_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SNOWSQL_USER: ${{ secrets.SF_USERNAME }}
          SNOWSQL_PWD: ${{ secrets.SF_PASSWORD }}
          SNOWSQL_ROLE: ${{ vars.SF_ROLE }}
          SNOWSQL_WAREHOUSE: ${{ vars.SF_WAREHOUSE }}
          SNOWSQL_DATABASE: ${{ vars.SF_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ vars.SF_SCHEMA_VALIDATE }}
          ENV_NAME: ${{ env.ENV_NAME }}

      - name: Creates pipeline
        env:
          STAGE_NAME: ${{vars.STAGE_NAME}}
          TRAIN_DIR: ${{vars.TRAIN_DIR}}
          INFERENCE_DIR: ${{vars.INFERENCE_DIR}}
          MODEL_NAME: ${{vars.MODEL_NAME}}
        run: 
         python $GITHUB_WORKSPACE/src/dags/dag_tasks.py

